name: 'Delete releases'
description: 'Delete releases in repository with optional filters'
inputs:
  name:
    description: 'Name of the release to delete'
    required: false
  keep:
    description: 'Number of matching releases to keep'
    required: false
    default: '0'
  types:
    description: 'Comma-separated list of release types to delete'
    required: true
    default: 'draft,prerelease,release'
runs:
  using: 'node16'
  main: 'dist/index.js'
